name: LaTeX CI

on:
  push:
    paths:
      - "**/*.tex"
      - .github/workflows/latex.yml
  pull_request:
    paths:
      - "**/*.tex"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            main.tex
          latexmk_use_lualatex: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-${{ github.sha }}
          path: kucharek.pdf
          if-no-files-found: error
